#Provide the taskId if you are updating the task
task_id: 'qq-11283'
# Name and desciption of your task
task_name: 'o.O'
task_description: 'info: https://github.com/zeyiya/task-template/'

# network value can be DEVELOPMENT , ARWEAVE or IPFS
task_executable_network: 'IPFS'

# Provide your web3.storage key as it is needed for uploading your metadata
secret_web3_storage_key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDRhMzUyYTMxYjhlQzY4MDFCMWFhMENDZmQ2ZjZEMDdmYTI5NDM4RjUiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2ODgxNzQ4ODUwNzcsIm5hbWUiOiJxcSJ9.yRSgW7yuCTmPtNABV2oRgr4a50CeF9kUGYGJap8HG6k'

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: '/home/qq/qq/task-template/dist/main.js'

# Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: ''

# Total round time of your task : it must be given in slots and each slot is rougly equal to 4ms
round_time: 60000

audit_window: 20000
submission_window: 20000

# Amounts in KOII

minimum_stake_amount: 0.01

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 10

bounty_amount_per_round: 1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value,description format shown below

author: '脑力大大'
description: 'info https://github.com/zeyiya/task-template/'
repositoryUrl: 'https://github.com/zeyiya/task-template'
imageUrl: 'https://i.pinimg.com/736x/a5/a7/bf/a5a7bf02c09d778ff7863f515b31ffff--screen-shot-screens.jpg'
requirementsTags:
  - type: CPU
    value: '0-core'
  - type: RAM
    value: '0 GB'
  - type: STORAGE
    value: '0 MB'
